# Generated by Django 3.2.6 on 2021-08-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0002_detallecompra_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDetalleCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrito.detallecompra')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrito.producto')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
