# Generated by Django 3.2.6 on 2021-08-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0003_auto_20210809_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
