# Generated by Django 3.2.6 on 2021-08-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0003_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='idDetalleCompra',
            new_name='detalleCompra',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='idProveedor',
            new_name='proveedor',
        ),
    ]
