# Generated by Django 3.2.6 on 2021-08-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0005_carrito_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modoPago', models.CharField(max_length=20)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrito.carrito')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precioVenta', models.FloatField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrito.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrito.producto')),
            ],
            options={
                'verbose_name': 'DetalleCarrito',
                'verbose_name_plural': 'DetalleCarritos',
            },
        ),
    ]
