# Generated by Django 3.2.6 on 2021-08-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0006_detallecarrito_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modoEnvio', models.CharField(max_length=20)),
                ('precioVenta', models.FloatField()),
                ('descripcion', models.CharField(max_length=50)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrito.carrito')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
