# Generated by Django 3.2.5 on 2021-09-12 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0009_auto_20210911_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcarrito', to='Carrito.carrito'),
        ),
    ]
