# Generated by Django 3.2.5 on 2021-09-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0010_alter_detallecarrito_carrito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='detalleCompra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidadStock',
        ),
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='precioCompra',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Carrito.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='precioVenta',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
