# Generated by Django 3.2.5 on 2021-09-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0011_auto_20210912_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='estado',
            new_name='confirmado',
        ),
    ]
