# Generated by Django 3.2.5 on 2021-09-13 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0012_rename_estado_carrito_confirmado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='confirmado',
        ),
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='Carrito.producto'),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='Carrito.producto'),
        ),
    ]
